version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
init: 
- cmd: git config --global core.autocrlf true 
- cmd: set DOTNET_VERSION_SUFFIX=%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: dotnet build MultiTask.sln -c release
test_script:
- cmd: dotnet test MultiTask.sln -c release --no-build
after_test:
- cmd: dotnet pack MultiTask.sln -c release --no-build -o nupkgs
artifacts:
- path: '**/*.nupkg'
- path: '**/*.snupkg'
